services:
    mysql:
        # Docker Hub image (also with version)
        image: mysql:5.7
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE:  db_test_laravel
        ## map the "external" 33306 port with the "internal" 3306
        ports:
            - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
            --health-cmd="mysqladmin ping"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=3
steps:
    checkout:
        name: Checkout code
        uses: actions/checkout@v2
    use-php:
        name: Install PHP versions
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php-versions }}
    php-version:
        name: 'Show PHP version'
        run: 'php -v'
    composer-install-dependencies:
        name: 'Install Dependencies'
        run: 'composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist'
    execute-phpcs:
        name: 'Execute Code Sniffer via phpcs'
        run: 'vendor/bin/phpcs --standard=PSR12 app'
    execute-phpstan:
        name: 'Execute Static Code Analysis'
        run: 'vendor/bin/phpstan analyse -c ./phpstan.neon --no-progress'
    execute-phpunit:
        name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
            DB_CONNECTION: mysql
            DB_DATABASE: db_test_laravel
            DB_PORT: 33306
            DB_USER: root
        run: vendor/bin/phpunit --testdox
    execute-pest:
        name: Execute tests (Unit and Feature tests) via Pest
        env:
            DB_CONNECTION: mysql
            DB_DATABASE: db_test_laravel
            DB_PORT: 33306
            DB_USER: root
        run: vendor/bin/pest
