name: hi-folks/maghic
'on':
    push:
        branches:
            - main
jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest]
                php-versions: ['8.0', '8.1']
        runs-on: '${{ matrix.os }}'
        services:
            mysql:
                image: 'mysql:latest'
                env: { MYSQL_ALLOW_EMPTY_PASSWORD: 'yes', MYSQL_DATABASE: db_test_laravel }
                ports: ['33306:3306']
                options: '--health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3'
        steps:
            -
                name: 'Checkout code'
                uses: actions/checkout@v2
            -
                name: 'Install PHP versions'
                uses: shivammathur/setup-php@v2
                with: { php-version: '${{ matrix.php-versions }}' }
            -
                name: 'Show PHP version'
                run: 'php -v'
            -
                name: 'Install Dependencies'
                run: 'composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist'
            -
                name: 'Execute Code Sniffer via phpcs'
                run: 'vendor/bin/phpcs --standard=PSR12 app'
            -
                name: 'Execute Static Code Analysis'
                run: 'vendor/bin/phpstan analyse -c ./phpstan.neon --no-progress'
            -
                name: 'Execute tests (Unit and Feature tests) via Pest'
                env: { DB_CONNECTION: mysql, DB_DATABASE: db_test_laravel, DB_PORT: 33306, DB_USER: root }
                run: vendor/bin/pest
env:
    MYSQL_IMAGE: 'mysql:latest'
